library(dplyr)
fuel<-read.csv("mpg.csv")
cat("Car which gives maximum city miles per gallon is:",fuel $manufacturer[which.max(fuel $cty)],fuel $model[which.max(fuel $cty)])
df<-filter(fuel,fuel$class=="compact")
df1<-filter(df,df$displ==min(df$displ))
un1<-unique(df1$manufacturer)
cat("\n the cars which gives minimum disp in compact is :",un1)
df2<-filter(fuel,fuel$class=="subcompact")
df3<-filter(df2,df2$displ==min(df2$displ))
un2<-unique(df3$manufacturer)
cat("\n the cars which gives minimum disp in subcompact is :",un2)